### ISSUE TITLE
Parsing the quotes on logfmt format 

### ISSUE THREAD

**Issue by vaibhavt19** [jkakar/logfmt-python#10]
I'm trying to parse quotes on logfmt format but, the value after the quote become new key with value "True".
`iimport logfmt
from logfmt import format
import io
raw_text=io.StringIO("ts=1579739313\"80007168")
rawdata=logfmt.parse(raw_text)
for i in rawdata:
    print(i)`

output
`{'ts': '1579739313', '80007168': True}
`

**Comment by jkakar** [comment]
Thanks for reporting this issue. This project has moved to https://github.com/wlonk/logfmt-python and the folks over there are likely best equipped to address this.
