### ISSUE TITLE
"ValueError: incomplete format" on LogfmtFormatter

### ISSUE THREAD

**Issue by anupamsr** [jkakar/logfmt-python#11]
Hi,

I am trying to use LogfmtFormatter as such:
```
h = Handler()
h.setFormatter(LogfmtFormatter())
```

And getting following error:

> --- Logging error ---
> Traceback (most recent call last):
>   File "/usr/lib/python3.7/logging/__init__.py", line 1025, in emit
>     msg = self.format(record)
>   File "/usr/lib/python3.7/logging/__init__.py", line 869, in format
>     return fmt.format(record)
>   File "/usr/lib/python3.7/site-packages/logfmt/formatter.py", line 27, in format
>     'at=%' % record.levelname,
> ValueError: incomplete format
> Call stack:
>   File "my.py", line 72, in <module>
>     logger.info('Hello, World!')
> Message: 'Hello, World!'
> Arguments: ()
> --- Logging error ---
> Traceback (most recent call last):
>   File "/usr/lib/python3.7/logging/__init__.py", line 1025, in emit
>     msg = self.format(record)
>   File "/usr/lib/python3.7/logging/__init__.py", line 869, in format
>     return fmt.format(record)
>   File "/usr/lib/python3.7/site-packages/logfmt/formatter.py", line 27, in format
>     'at=%' % record.levelname,
> ValueError: incomplete format
> Call stack:
>   File "my.py", line 73, in <module>
>     logger.debug('Hello, World!')
> Message: 'Hello, World!'
> Arguments: ()

Looking at the code, is a %s missing?

**Comment by jkakar** [comment]
Thanks for reporting this issue! I haven't maintained this project for many years. https://github.com/wlonk/logfmt-python took it over awhile ago and is probably better suited to addressing this bug.
